### ISSUE TITLE
Add/use some register definitions

### ISSUE THREAD

**Issue by Daft-Freak** [Daft-Freak/DERP#1]
It's mostly magic numbers (with some comments). Maybe just use the hardware_regs headers from the SDK somehow?

**Comment by Gadgetoid** [comment]
I was looking at stuff like https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_pio/include/hardware/pio_instructions.h which looks really useful, but also includes "pico.h" which includes "types.h" and "version.h" (which requires processing.)

All the `regs/<peripheral>.h` files are self contained, though, so it would be logical to include *all the things*.

Also the structs look useful, eg: https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2040/hardware_structs/include/hardware/structs/pio.h

But these pull in https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_base/include/hardware/address_mapped.h

Which I'm pretty sure can be overridden?

**Comment by Daft-Freak** [comment]
I guess the SDK isn't so big that adding the whole thing as a submodule to get at the headers would be that bad...

Really should clean up some of the "magic switch" mess, too busy adding GDB/USB servers apparently.

**Comment by Daft-Freak** [comment]
Well, it works: https://github.com/Daft-Freak/DERP/compare/main...register-demagic

Probably should've set some include dirs instead of the cmake hacks though... Now to see what the rest looks like before I find something more exciting to do :laughing:

**Comment by Gadgetoid** [comment]
Aaah, way more glanceable! Nice. What is Pico SDK if not a bunch of cmake hacks, tbf? :laughing:

**Comment by Daft-Freak** [comment]
Hmm, a nice side-effect of this is getting the documentation on hover... Also think I fixed some bugs while going through everything. (...and reminded of a bunch of other problems... and still not done...)

> What is Pico SDK if not a bunch of cmake hacks, tbf? laughing

Maybe, but I've definitely seen worse... and I'm definitely using it a bit wrong here. :laughing: (Guess there's not much chance of things breaking, shouldn't need to update the SDK... :thinking: )
